name: Test Shared Package

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

concurrency: 
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test:ci

      - name: Build
        run: |
          npm run build
