name: Test Shared Package

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main

concurrency: 
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
              
      - name: Run linter
        run: |
          npm run lint

      - name: Run tests
        run: |
          npm run test:ci

      - name: Sync TiFAPISchema with OpenAPI specs.json
        run: |
          cp specs.json OriginalSpecs.json
          npm run genapispecs
          if ! diff specs.json OriginalSpecs.json; then
            echo "specs.json is not up to date. Please re-run 'npm run genapispecs' and commit the updated version to this branch."
            exit 1
          fi

      - name: Validate openapi specs
        run: |
          npm run genapispecs
      
      # TODO - run openapi specs linter from ibm-openapi-validator

      - name: Build
        run: |
          npm run build
